// Code generated by aic-ent, DO NOT EDIT
// Code generated by aic-ent, DO NOT EDIT
// Code generated by aic-ent, DO NOT EDIT

package dao

import (
	"context"
	db "github.com/frochyzhang/ag-core/ag/ag_db/gormdb"
	"github.com/frochyzhang/ag-layout/internal/data/model"
)

type IGreeterDao interface {
	InsertOne(ctx context.Context, arg *model.Greeter) (int64, error)
	FindByPrimaryKey(ctx context.Context, Hello string) (*model.Greeter, error)
	UpdateByPrimaryKey(ctx context.Context, arg *model.Greeter) (int64, error)
	UpdateByPriIgnoreNullCols(ctx context.Context, arg *model.Greeter) (int64, error)
	DeleteByPrimaryKey(ctx context.Context, Hello string) (int64, error)
}

type GreeterDao struct {
	*db.Repository
}

// NewGreeterDao get dao instance
func NewGreeterDao() IGreeterDao {
	return &GreeterDao{
		Repository: nil,
	}
}

func (dao *GreeterDao) InsertOne(ctx context.Context, arg *model.Greeter) (int64, error) {
	//result := dao.DB(ctx).Create(arg)
	return 1, nil
}

func (dao *GreeterDao) FindByPrimaryKey(ctx context.Context, Hello string) (*model.Greeter, error) {
	findRes := &model.Greeter{}
	result := dao.DB(ctx).Where("Hello", Hello).Find(findRes)
	return findRes, result.Error
}

func (dao *GreeterDao) UpdateByPrimaryKey(ctx context.Context, arg *model.Greeter) (int64, error) {
	result := dao.DB(ctx).Save(arg)
	return result.RowsAffected, result.Error
}

func (dao *GreeterDao) UpdateByPriIgnoreNullCols(ctx context.Context, arg *model.Greeter) (int64, error) {
	result := dao.DB(ctx).Model(arg).Updates(arg)
	return result.RowsAffected, result.Error
}

func (dao *GreeterDao) DeleteByPrimaryKey(ctx context.Context, Hello string) (int64, error) {
	result := dao.DB(ctx).Where("Hello", Hello).Delete(&model.Greeter{})
	return result.RowsAffected, result.Error
}
