// Code generated by protoc-gen-go-http. DO NOT EDIT.
// Code generated by protoc-gen-go-http. DO NOT EDIT.
// Code generated by protoc-gen-go-http. DO NOT EDIT.
// Generate time:  2006-01-02 15:04:05

package service

import (
	"context"
	"log"
	"time"

	mw "github.com/frochyzhang/ag-core/ag/ag_ext"
	pb "github.com/frochyzhang/ag-layout/api/helloworld"
)

// ===================== 代理实现 =====================
type HelloProxy struct {
	service  pb.HelloServer // 原始服务实例
	handlers map[string]mw.HandlerFunc
}

func NewHelloProxy(service pb.HelloServer, mws []mw.Middleware) pb.HelloServer {
	proxy := &HelloProxy{
		service:  service,
		handlers: make(map[string]mw.HandlerFunc),
	}

	proxy.handlers["CreateHello"] = mw.RegisterHandler("CreateHello", mws, func(ctx context.Context, req interface{}) (interface{}, error) {
		// 最终调用原始服务方法
		return proxy.service.CreateHello(ctx, req.(*pb.Hello1Request))
	})
	return proxy
}

// ======== Hello 代理方法 ========
func (p *HelloProxy) CreateHello(ctx context.Context, in *pb.Hello1Request) (*pb.Hello1Reply, error) {
	start := time.Now()
	methodName := "CreateHello"

	// 获取处理链
	handler := p.handlers[methodName]

	// 执行调用链
	res, err := handler(ctx, in)
	if err != nil {
		log.Printf("[%s] failed in %v: %v", methodName, time.Since(start), err)
		return nil, err
	}

	log.Printf("[%s] success in %v", methodName, time.Since(start))
	return res.(*pb.Hello1Reply), nil
}
