// Code generated by protoc-gen-go-http. DO NOT EDIT.
// Code generated by protoc-gen-go-http. DO NOT EDIT.
// Code generated by protoc-gen-go-http. DO NOT EDIT.
// Generate time:  2006-01-02 15:04:05

package service

import (
	"github.com/frochyzhang/ag-layout/api/helloworld"
	"go.uber.org/fx"
)

var FxServiceModule = fx.Module("fx-service",
	fx.Provide(
		NewGreeterService,
		NewHelloService,
	),
	fx.Provide(
		fx.Annotate(
			NewGreeterProxy,
			fx.As(new(helloworld.GreeterServer)),
		),
	),
	fx.Provide(
		fx.Annotate(
			NewHelloProxy,
			fx.As(new(helloworld.HelloServer)),
		),
	),
)
