// Code generated by aic-ent, DO NOT EDIT
// Code generated by aic-ent, DO NOT EDIT
// Code generated by aic-ent, DO NOT EDIT

package model

import 
import (
	"fmt"
)

// Greeter mapped from table greeter
	Hello string `gorm:"column:Hello;not null" json:"Hello"`
   Hello  string `gorm:"column:Hello;not null" json:"Hello"`
}

// TableName greeter table name
	return "greeter"
   return "greeter"
}

	if owner == nil {
		return nil
	}
	return &Greeter{
		Hello: owner.Hello,
	}
   }
}

	if owner == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Greeter:(%+v)", *owner)
    return fmt.Sprintf("Greeter:(%+v)", *owner)
}
}