// Code generated by protoc-gen-go-http. DO NOT EDIT.
// Code generated by protoc-gen-go-http. DO NOT EDIT.
// Code generated by protoc-gen-go-http. DO NOT EDIT.
// Generate time: 2006-01-02 15:04:05
// versions:
// - protoc-gen-go-http v1.0.2
// - protoc             v5.28.0
// source: helloworld/greeter.proto

package helloworld

import (
	context "context"
	app "github.com/cloudwego/hertz/pkg/app"
	server "github.com/cloudwego/hertz/pkg/app/server"
	consts "github.com/cloudwego/hertz/pkg/protocol/consts"
	hertz "github.com/frochyzhang/ag-core/ag/ag_server/hertz"
	fx "go.uber.org/fx"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = app.FS{}
var _ = server.Hertz{}
var _ = consts.StatusOK
var _ = hertz.Server{}
var _ = fx.Self()

const OperationGreeterCreateGreeter = "/helloworld.Greeter/CreateGreeter"
const OperationGreeterPutGreeter = "/helloworld.Greeter/PutGreeter"

type GreeterHTTPServer interface {
	// CreateGreeter Create a greeter
	CreateGreeter(context.Context, *HelloRequest) (*HelloReply, error)
	// PutGreeter put a greeter
	PutGreeter(context.Context, *HelloRequest) (*HelloReply, error)
}

func Register_Greeter_CreateGreeter_HTTPServer(srv GreeterHTTPServer) hertz.Option {
	return hertz.WithRoute(&hertz.Route{
		HttpMethod:   "POST",
		RelativePath: "/helloworld",
		Handlers:     append(make([]app.HandlerFunc, 0), _Greeter_CreateGreeter0_HTTP_Handler(srv)),
	})
}
func Register_Greeter_PutGreeter_HTTPServer(srv GreeterHTTPServer) hertz.Option {
	return hertz.WithRoute(&hertz.Route{
		HttpMethod:   "PUT",
		RelativePath: "/helloworld",
		Handlers:     append(make([]app.HandlerFunc, 0), _Greeter_PutGreeter0_HTTP_Handler(srv)),
	})
}

func _Greeter_CreateGreeter0_HTTP_Handler(srv GreeterHTTPServer) func(ctx context.Context, c *app.RequestContext) {
	return func(ctx context.Context, c *app.RequestContext) {
		var in = new(HelloRequest)
		if err := c.BindByContentType(in); err != nil {
			c.String(consts.StatusBadRequest, err.Error())
			return
		}
		if err := c.BindQuery(in); err != nil {
			c.String(consts.StatusBadRequest, err.Error())
			return
		}
		reply, err := srv.CreateGreeter(ctx, in)
		if err != nil {
			c.String(consts.StatusInternalServerError, err.Error())
		}
		c.JSON(consts.StatusOK, reply)
	}
}

func _Greeter_PutGreeter0_HTTP_Handler(srv GreeterHTTPServer) func(ctx context.Context, c *app.RequestContext) {
	return func(ctx context.Context, c *app.RequestContext) {
		var in = new(HelloRequest)
		if err := c.BindByContentType(in); err != nil {
			c.String(consts.StatusBadRequest, err.Error())
			return
		}
		if err := c.BindQuery(in); err != nil {
			c.String(consts.StatusBadRequest, err.Error())
			return
		}
		reply, err := srv.PutGreeter(ctx, in)
		if err != nil {
			c.String(consts.StatusInternalServerError, err.Error())
		}
		c.JSON(consts.StatusOK, reply)
	}
}

var FxGreeterHTTPModule = fx.Module("fx_Greeter_HTTP",
	fx.Provide(

		fx.Annotate(
			Register_Greeter_CreateGreeter_HTTPServer,
			fx.ResultTags(`group:"hertz_router_options"`),
		),

		fx.Annotate(
			Register_Greeter_PutGreeter_HTTPServer,
			fx.ResultTags(`group:"hertz_router_options"`),
		),
	),
)
