// Code generated by protoc-gen-go-http. DO NOT EDIT.
// Code generated by protoc-gen-go-http. DO NOT EDIT.
// Code generated by protoc-gen-go-http. DO NOT EDIT.
// Generate time: 2006-01-02 15:04:05
// versions:
// - protoc-gen-go-http v1.0.5
// - protoc             v5.28.0
// source: helloworld/hello.proto

package helloworld

import (
	context "context"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

type HelloServer interface {
	// CreateHello Create a Hello
	CreateHello(context.Context, *Hello1Request) (*Hello1Reply, error)
}
