// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.0
// source: helloworld/hello.proto

package helloworld

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the user's name.
type Hello1Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello1Request) Reset() {
	*x = Hello1Request{}
	mi := &file_helloworld_hello_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello1Request) ProtoMessage() {}

func (x *Hello1Request) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_hello_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello1Request.ProtoReflect.Descriptor instead.
func (*Hello1Request) Descriptor() ([]byte, []int) {
	return file_helloworld_hello_proto_rawDescGZIP(), []int{0}
}

func (x *Hello1Request) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// The response message containing the greetings
type Hello1Reply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello1Reply) Reset() {
	*x = Hello1Reply{}
	mi := &file_helloworld_hello_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello1Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello1Reply) ProtoMessage() {}

func (x *Hello1Reply) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_hello_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello1Reply.ProtoReflect.Descriptor instead.
func (*Hello1Reply) Descriptor() ([]byte, []int) {
	return file_helloworld_hello_proto_rawDescGZIP(), []int{1}
}

func (x *Hello1Reply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_helloworld_hello_proto protoreflect.FileDescriptor

const file_helloworld_hello_proto_rawDesc = "" +
	"\n" +
	"\x16helloworld/hello.proto\x12\n" +
	"helloworld\x1a\x1cgoogle/api/annotations.proto\"#\n" +
	"\rHello1Request\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"'\n" +
	"\vHello1Reply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xb0\x01\n" +
	"\x05Hello\x12T\n" +
	"\vCreateHello\x12\x19.helloworld.Hello1Request\x1a\x17.helloworld.Hello1Reply\"\x11\x82\xd3\xe4\x93\x02\v:\x01*\"\x06/hello\x12Q\n" +
	"\bPutHello\x12\x19.helloworld.Hello1Request\x1a\x17.helloworld.Hello1Reply\"\x11\x82\xd3\xe4\x93\x02\v:\x01*\x1a\x06/helloB_\n" +
	"\x1fcom.allinfinance.api.helloworldB\x0fHelloworldProtoP\x01Z)allinfinance.com/ag-layout/api/helloworldb\x06proto3"

var (
	file_helloworld_hello_proto_rawDescOnce sync.Once
	file_helloworld_hello_proto_rawDescData []byte
)

func file_helloworld_hello_proto_rawDescGZIP() []byte {
	file_helloworld_hello_proto_rawDescOnce.Do(func() {
		file_helloworld_hello_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_helloworld_hello_proto_rawDesc), len(file_helloworld_hello_proto_rawDesc)))
	})
	return file_helloworld_hello_proto_rawDescData
}

var file_helloworld_hello_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_helloworld_hello_proto_goTypes = []any{
	(*Hello1Request)(nil), // 0: helloworld.Hello1Request
	(*Hello1Reply)(nil),   // 1: helloworld.Hello1Reply
}
var file_helloworld_hello_proto_depIdxs = []int32{
	0, // 0: helloworld.Hello.CreateHello:input_type -> helloworld.Hello1Request
	0, // 1: helloworld.Hello.PutHello:input_type -> helloworld.Hello1Request
	1, // 2: helloworld.Hello.CreateHello:output_type -> helloworld.Hello1Reply
	1, // 3: helloworld.Hello.PutHello:output_type -> helloworld.Hello1Reply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_helloworld_hello_proto_init() }
func file_helloworld_hello_proto_init() {
	if File_helloworld_hello_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_helloworld_hello_proto_rawDesc), len(file_helloworld_hello_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_helloworld_hello_proto_goTypes,
		DependencyIndexes: file_helloworld_hello_proto_depIdxs,
		MessageInfos:      file_helloworld_hello_proto_msgTypes,
	}.Build()
	File_helloworld_hello_proto = out.File
	file_helloworld_hello_proto_goTypes = nil
	file_helloworld_hello_proto_depIdxs = nil
}
