env: local
nacos:
  config:
    enable: true
    serveraddr: 127.0.0.1:8848
    namespace: test
    username: nacos
    password: nacos
    dataids:
      - dataid: wksd.yaml
        type: yaml
        group: DEFAULT_GROUP
        autorefresh: true

log:
  log_level: debug
  log_file_name: "./storage/logs/server.log"
  max_backups: 30
  max_age: 7
  max_size: 1024
  compress: false
  console: true