env: local
http:
  #  host: 0.0.0.0
  host: 127.0.0.1
  # port: 3306
  port: 8000
kitex:
  # host: 127.0.0.1
  port: 8001
  endpoint: hzw
  client:
    pyyservice:
      endpoint: pyy
    songbservice:
      endpoint: songb
data:
  db:
    user:
     driver: ibmdb
     dsn: HOSTNAME=192.168.105.63;DATABASE=testdb;PORT=50001;UID=db2inst1;PWD=db2inst1;AUTHENTICATION=SERVER;CurrentSchema=ENTTEST
#      driver: sqlite
#      dsn: storage/nunu-test.db?_busy_timeout=5000
      #  driver: mysql
      #  dsn: root:root@tcp(127.0.0.1:3306)/mdms?charset=utf8mb4&parseTime=True&loc=Local
  #    user:
  #      driver: postgres
  #      dsn: host=localhost user=gorm password=gorm dbname=gorm port=9920 sslmode=disable TimeZone=Asia/Shanghai
nacos:
  config:
    enableconfig: true
    enablenaming: true
    serveraddr: 10.25.30.105:31983
    namespace: test
    username: nacos
    password: nacos
    dataids:
      - dataid: "wksd.yaml"
        group: "DEFAULT_GROUP"
        type: yaml
#      - dataid: "aic_2.yaml"
#        group: "DEFAULT_GROUP"
#        type: yaml

# nacos:
#   enable: true
#   config:
# #     user:
# #       #address: 192.168.33.10
#       address: 192.168.105.63:8813
#       port: 8813
#       namespace: aic-dev
#       dataidlist:
#         - dataid: "aic_1.yaml"
#           group: "DEFAULT_GROUP"
#           type: yaml
#         - dataid: "aic_2.yaml"
#           group: "DEFAULT_GROUP"
#           type: yaml
# #      group: aic
#       username: nacos
#       password: nacos
#       log:
#         timeout_ms: 5000
#         not_load_cache_at_start: true
#         log_dir: ./storage/nacos/log
#         cache_dir: ./storage/nacos/cache
#         log_level: "info"




log:
  log_level: debug
  encoding: console           # json or console
  log_file_name: "./storage/logs/server.log"
  max_backups: 30
  max_age: 7
  max_size: 1024
  compress: true