package service

import (
	"bytes"
	"fmt"
	"html/template"
	"time"
)

//nolint:lll
var serviceTemplate = `
{{- /* delete empty line */ -}}
package service

import (
	{{- if .UseContext }}
	"context"
	{{- end }}
	{{- if .UseIO }}
	"io"
	{{- end }}

	pb "{{ .Package }}"
	{{- if .GoogleEmpty }}
	"google.golang.org/protobuf/types/known/emptypb"
	{{- end }}
)

type {{ .Service }}Service struct {
}

func New{{ .Service }}Service() *{{ .Service }}Service {
	return &{{ .Service }}Service{}
}

{{- $s1 := "google.protobuf.Empty" }}
{{ range .AllMethods }}
{{- if eq .Type 1 }}
func (s *{{ .Service }}Service) {{ .Name }}(ctx context.Context, in {{ if eq .Request $s1 }}*emptypb.Empty{{ else }}*pb.{{ .Request }}{{ end }}) ({{ if eq .Reply $s1 }}*emptypb.Empty{{ else }}*pb.{{ .Reply }}{{ end }}, error) {
	return {{ if eq .Reply $s1 }}&emptypb.Empty{}{{ else }}&pb.{{ .Reply }}{}{{ end }}, nil
}

{{- else if eq .Type 2 }}
func (s *{{ .Service }}Service) {{ .Name }}(conn pb.{{ .Service }}_{{ .Name }}Server) error {
	for {
		in, err := conn.Recv()
		if err == io.EOF {
			return nil
		}
		if err != nil {
			return err
		}
		
		err = conn.Send(&pb.{{ .Reply }}{})
		if err != nil {
			return err
		}
	}
}

{{- else if eq .Type 3 }}
func (s *{{ .Service }}Service) {{ .Name }}(conn pb.{{ .Service }}_{{ .Name }}Server) error {
	for {
		in, err := conn.Recv()
		if err == io.EOF {
			return conn.SendAndClose(&pb.{{ .Reply }}{})
		}
		if err != nil {
			return err
		}
	}
}

{{- else if eq .Type 4 }}
func (s *{{ .Service }}Service) {{ .Name }}(in {{ if eq .Request $s1 }}*emptypb.Empty
{{ else }}*pb.{{ .Request }}{{ end }}, conn pb.{{ .Service }}_{{ .Name }}Server) error {
	for {
		err := conn.Send(&pb.{{ .Reply }}{})
		if err != nil {
			return err
		}
	}
}

{{- end }}
{{- end }}
`

type MethodType uint8

const (
	unaryType          MethodType = 1
	twoWayStreamsType  MethodType = 2
	requestStreamsType MethodType = 3
	returnsStreamsType MethodType = 4
)

// Module is a fx server definition
type Module struct {
	Packages []string
	Names    []Annotate
}

type Annotate struct {
	Brief string
	Name  string
}

// Service is a proto service.
type Service struct {
	Package     string
	Service     string
	Methods     []*Method
	GoogleEmpty bool

	UseIO      bool
	UseContext bool
}

// Method is a proto method.
type Method struct {
	Service string
	Name    string
	Request string
	Reply   string

	// type: unary or stream
	Type MethodType
}

func (s *Service) execute() ([]byte, error) {
	const empty = "google.protobuf.Empty"
	buf := new(bytes.Buffer)
	for _, method := range s.Methods {
		if (method.Type == unaryType && (method.Request == empty || method.Reply == empty)) ||
			(method.Type == returnsStreamsType && method.Request == empty) {
			s.GoogleEmpty = true
		}
		if method.Type == twoWayStreamsType || method.Type == requestStreamsType {
			s.UseIO = true
		}
		if method.Type == unaryType {
			s.UseContext = true
		}
	}
	tmpl, err := template.New("service").Parse(serviceTemplate)
	if err != nil {
		return nil, err
	}
	if err := tmpl.Execute(buf, s); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func (m *Module) execute() ([]byte, error) {
	buf := new(bytes.Buffer)
	prefix := "// Code generated by protoc-gen-go-http. DO NOT EDIT."
	prefix = fmt.Sprintln(prefix, "// Code generated by protoc-gen-go-http. DO NOT EDIT.")
	prefix = fmt.Sprintln(prefix, "// Code generated by protoc-gen-go-http. DO NOT EDIT.")

	prefix = fmt.Sprintln(prefix, "// Generate time: ", time.DateTime)

	tmpl, err := template.New("service-module").Parse(prefix + serviceModuleTemplate)
	if err != nil {
		return nil, err
	}
	if err := tmpl.Execute(buf, m); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

//nolint:lll
var serviceModuleTemplate = `
package service

import ({{ range .Packages }}
	"{{.}}"
	{{- end }}
	"go.uber.org/fx"
)

var FxServiceModule = fx.Module("fx-service",{{ range .Names }}
	fx.Provide(
		fx.Annotate(
			New{{ .Name }}Service,
			fx.As(new({{ .Brief }}.{{ .Name }}HTTPServer)),
			fx.As(new({{ .Brief }}.{{ .Name }}GRPCServer)),
		),
	),
	{{- end }}
)
`
