name: Build and Release aif-go

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整历史，确保标签可用

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.4'

      - name: Verify structure
        run: |
          echo "Current directory: $(pwd)"
          ls -la generator/aif-go
          test -f generator/aif-go/main.go || exit 1

      - name: Build aif-go
        working-directory: generator/aif-go
        run: |
          go build -v -o aif-go .

      - name: Test binary
        run: |
          ./generator/aif-go/aif-go --version

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            generator/aif-go/aif-go
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
