name: Build and Release aif-go

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整历史，确保标签可用
      - name: Kratos
        run: |
          cd generator/aif-go
          go build ./...
          go test ./...
